# GitHub Labels Configuration
# These labels will be available for use on issues and pull requests

- name: run-acceptance-tests
  color: "d73a4a"
  description: "Trigger expensive acceptance tests on this PR (runs against real IBM Cloud)"

- name: bug
  color: "d73a4a"
  description: "Something isn't working"

- name: enhancement
  color: "a2eeef"
  description: "New feature or request"

- name: documentation
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: dependencies
  color: "0366d6"
  description: "Pull requests that update a dependency file"

- name: good first issue
  color: "7057ff"
  description: "Good for newcomers"

- name: help wanted
  color: "008672"
  description: "Extra attention is needed"

- name: security
  color: "d73a4a"
  description: "Security-related issue or PR"

- name: breaking change
  color: "d93f0b"
  description: "This PR contains breaking changes"